### PR TITLE
Create __init__.py

### LINKED ISSUE #7: issue
when ever I run main.py I get an Import error from the sprint.py file say cannot import name 'colors' from 'scripts' (unknown location) cloud you please let me know if I am doing something wrong if so can you let me know so i can stop doing it

### PR DESCRIPTION
**Pull request by Ccode-lang**
closes #7

### CODE REVIEW

**Comment by Ccode-lang** [comment]
I'm going to test this later to see if the problem is fixed.

**Comment by CPScript** [comment]
ok

**Comment by CPScript** [comment]
i already fixed the problem??????

**Comment by Ccode-lang** [comment]
No this pull request has the code in it to fix the repo.  When someone wants to add code to your repo they will open a PR.  You can look through their code and if you like it you can press the merge button to add it to your repository.

**Comment by Ccode-lang** [comment]
The code seems to be fixed now and the imports work.

**Comment by CPScript** [comment]
alright

**Pull request merged**
