### PR TITLE
Changing the main.py file so it doesn't clone the repository again

### PR DESCRIPTION
**Pull request by devarxify**
The main.py was (for some reason) cloning the repository again (?)

Anyways, there are a couple more errors to fix in the Kahoot/ folder but I'll fix those when I have time

### CODE REVIEW

**Comment by CPScript** [comment]
Its supposed to do that for updates...

**Comment by CPScript** [comment]
Womp Womp

**Review by CPScript — APPROVED** [review]
w

**Comment by CPScript** [comment]
I will update the script so that it has a script where you can update the tool, (this is gonna be more complex than it has to be of course), but if you find any other errors i'd gladly fix them!

**Comment by devarxify** [comment]
alright!

**Pull request closed without merging**
